#!/usr/bin/env python3
"""
vuln_intel.py - Vulnerability intelligence enrichment for the security pipeline.

Reads pip-audit JSON output and enriches CVE findings with:

    - CVSS score and severity from the NVD API
    - EPSS score and percentile from FIRST.org
    - CISA Known Exploited Vulnerabilities (KEV) status

The script then combines these signals into a deterministic risk tier.

Important:
    - KEV status overrides the numerical scoring model.
    - Intelligence lookup failures are recorded explicitly.
    - Missing intelligence is not silently treated as a clean result.
    - This script only consumes the SCA report generated by pip-audit.
"""

import argparse
import json
import os
import sys
import time
from typing import Any

import requests


NVD_API_URL = "https://services.nvd.nist.gov/rest/json/cves/2.0"
EPSS_API_URL = "https://api.first.org/data/v1/epss"
KEV_FEED_URL = (
    "https://www.cisa.gov/sites/default/files/feeds/"
    "known_exploited_vulnerabilities.json"
)

# NVD rate limits.
NVD_DELAY_NO_KEY = 6.5
NVD_DELAY_WITH_KEY = 0.7

EPSS_BATCH_SIZE = 100


def load_sca_findings(path: str) -> list[dict[str, Any]]:
    """Flatten pip-audit JSON into one finding per package/advisory/CVE."""

    with open(path, encoding="utf-8") as f:
        data = json.load(f)

    findings: list[dict[str, Any]] = []

    for dep in data.get("dependencies", []):
        for vuln in dep.get("vulns", []):
            cve_ids = [
                alias
                for alias in vuln.get("aliases", [])
                if alias.startswith("CVE-")
            ]

            if not cve_ids:
                findings.append(
                    {
                        "package": dep["name"],
                        "installed_version": dep["version"],
                        "advisory_id": vuln["id"],
                        "cve_id": None,
                        "fix_versions": vuln.get("fix_versions", []),
                    }
                )
                continue

            for cve in cve_ids:
                findings.append(
                    {
                        "package": dep["name"],
                        "installed_version": dep["version"],
                        "advisory_id": vuln["id"],
                        "cve_id": cve,
                        "fix_versions": vuln.get("fix_versions", []),
                    }
                )

    return findings


def fetch_cvss(
    cve_id: str,
    api_key: str | None,
) -> dict[str, Any]:
    """Fetch the newest available CVSS metric from NVD."""

    headers = {"apiKey": api_key} if api_key else {}

    response = requests.get(
        NVD_API_URL,
        params={"cveId": cve_id},
        headers=headers,
        timeout=30,
    )
    response.raise_for_status()

    vulnerabilities = response.json().get("vulnerabilities", [])

    if not vulnerabilities:
        return {
            "cvss_score": None,
            "cvss_severity": None,
            "cvss_version": None,
        }

    metrics = vulnerabilities[0]["cve"].get("metrics", {})

    # Prefer the newest CVSS version available.
    metric_order = (
        "cvssMetricV40",
        "cvssMetricV31",
        "cvssMetricV30",
        "cvssMetricV2",
    )

    for metric_key in metric_order:
        metric_entries = metrics.get(metric_key)

        if not metric_entries:
            continue

        metric = metric_entries[0]
        cvss_data = metric.get("cvssData", {})

        return {
            "cvss_score": cvss_data.get("baseScore"),
            "cvss_severity": cvss_data.get(
                "baseSeverity",
                metric.get("baseSeverity"),
            ),
            "cvss_version": cvss_data.get("version"),
        }

    return {
        "cvss_score": None,
        "cvss_severity": None,
        "cvss_version": None,
    }


def fetch_epss_batch(
    cve_ids: list[str],
) -> dict[str, dict[str, float]]:
    """Fetch EPSS scores in batches."""

    results: dict[str, dict[str, float]] = {}

    for i in range(0, len(cve_ids), EPSS_BATCH_SIZE):
        batch = cve_ids[i : i + EPSS_BATCH_SIZE]

        response = requests.get(
            EPSS_API_URL,
            params={"cve": ",".join(batch)},
            timeout=30,
        )
        response.raise_for_status()

        for row in response.json().get("data", []):
            results[row["cve"]] = {
                "epss_score": float(row["epss"]),
                "epss_percentile": float(row["percentile"]),
            }

    return results


def fetch_kev_ids() -> set[str]:
    """Download the CISA KEV catalog and return its CVE IDs."""

    response = requests.get(KEV_FEED_URL, timeout=30)
    response.raise_for_status()

    return {
        vulnerability["cveID"]
        for vulnerability in response.json().get("vulnerabilities", [])
    }


def classify_risk(
    cvss_score: float | None,
    epss_score: float | None,
    in_kev: bool,
) -> str:
    """
    Combine CVSS, EPSS, and KEV into a deterministic risk tier.

    KEV overrides the numerical model because the CVE is known to
    have been exploited in the wild.

    Otherwise:
        normalized CVSS = CVSS / 10
        EPSS = probability from 0 to 1

    Both signals receive equal weight.
    """

    if in_kev:
        return "CRITICAL"

    if cvss_score is None and epss_score is None:
        return "UNKNOWN"

    cvss_norm = (cvss_score or 0.0) / 10.0
    epss_norm = epss_score or 0.0

    blended = (cvss_norm * 0.5) + (epss_norm * 0.5)

    if blended >= 0.7:
        return "CRITICAL"

    if blended >= 0.5:
        return "HIGH"

    if blended >= 0.3:
        return "MEDIUM"

    return "LOW"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Enrich pip-audit findings with CVSS, EPSS, and KEV data."
    )

    parser.add_argument(
        "--input",
        required=True,
        help="pip-audit JSON output",
    )

    parser.add_argument(
        "--output",
        required=True,
        help="enriched risk report path",
    )

    args = parser.parse_args()

    findings = load_sca_findings(args.input)

    cve_findings = [
        finding
        for finding in findings
        if finding["cve_id"]
    ]

    unscored_findings = [
        finding
        for finding in findings
        if not finding["cve_id"]
    ]

    # If pip-audit produced no CVE mappings, still create a valid report.
    if not cve_findings:
        print("No CVE-mapped findings from SCA.")

        report = []

        for finding in unscored_findings:
            report.append(
                {
                    **finding,
                    "kev_listed": False,
                    "risk_tier": "UNKNOWN",
                    "intelligence_status": "not_applicable",
                    "intelligence_errors": [],
                }
            )

        with open(args.output, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2)

        return 0

    unique_cves = sorted(
        {finding["cve_id"] for finding in cve_findings}
    )

    print(
        f"Enriching {len(unique_cves)} unique CVE(s)..."
    )

    api_key = os.environ.get("NVD_API_KEY")

    nvd_delay = (
        NVD_DELAY_WITH_KEY
        if api_key
        else NVD_DELAY_NO_KEY
    )

    # ------------------------------------------------------------------
    # NVD / CVSS
    # ------------------------------------------------------------------

    cvss_by_cve: dict[str, dict[str, Any]] = {}
    nvd_failed = False

    for i, cve in enumerate(unique_cves):
        try:
            cvss_by_cve[cve] = fetch_cvss(cve, api_key)

        except requests.RequestException as exc:
            nvd_failed = True

            print(
                f"  NVD lookup failed for {cve}: {exc}",
                file=sys.stderr,
            )

            cvss_by_cve[cve] = {
                "cvss_score": None,
                "cvss_severity": None,
                "cvss_version": None,
            }

        if i < len(unique_cves) - 1:
            time.sleep(nvd_delay)

    # ------------------------------------------------------------------
    # EPSS
    # ------------------------------------------------------------------

    epss_by_cve: dict[str, dict[str, float]] = {}
    epss_failed = False

    try:
        epss_by_cve = fetch_epss_batch(unique_cves)

    except requests.RequestException as exc:
        epss_failed = True

        print(
            f"  EPSS lookup failed: {exc}",
            file=sys.stderr,
        )

    # ------------------------------------------------------------------
    # CISA KEV
    # ------------------------------------------------------------------

    kev_ids: set[str] = set()
    kev_failed = False

    try:
        kev_ids = fetch_kev_ids()

    except requests.RequestException as exc:
        kev_failed = True

        print(
            f"  KEV feed download failed: {exc}",
            file=sys.stderr,
        )

    # ------------------------------------------------------------------
    # Build final report
    # ------------------------------------------------------------------

    report: list[dict[str, Any]] = []

    for finding in unscored_findings:
        report.append(
            {
                **finding,
                "kev_listed": False,
                "risk_tier": "UNKNOWN",
                "intelligence_status": "not_applicable",
                "intelligence_errors": [],
            }
        )

    for finding in cve_findings:
        cve = finding["cve_id"]

        cvss = cvss_by_cve.get(cve, {})
        epss = epss_by_cve.get(cve, {})

        in_kev = cve in kev_ids

        errors: list[str] = []

        if nvd_failed:
            errors.append("nvd_lookup_failed")

        if epss_failed:
            errors.append("epss_lookup_failed")

        if kev_failed:
            errors.append("kev_lookup_failed")

        if errors:
            intelligence_status = "partial"
        else:
            intelligence_status = "complete"

        enriched = {
            **finding,
            **cvss,
            **epss,
            "kev_listed": in_kev,
            "risk_tier": classify_risk(
                cvss.get("cvss_score"),
                epss.get("epss_score"),
                in_kev,
            ),
            "intelligence_status": intelligence_status,
            "intelligence_errors": errors,
        }

        report.append(enriched)

    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)

    print(
        f"Wrote {len(report)} finding(s) to {args.output}"
    )

    return 0


if __name__ == "__main__":
    sys.exit(main())
